name: "README mountain"
description: "This action runs a μ-lab hackathon"
author: "μ-lab"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Get dependencies
      run: go get -v -t -d ./...

    - run: go run ${{ github.action_path }}/main.go
      shell: bash