name: "README mountain"
description: "This action runs a μ-lab hackathon"
author: "μ-lab"

runs:
  using: "composite"
  steps:
    - name: clone
      run: |
        git clone https://github.com/suba327777/README.Mountain.git
        cd README.Mountain 
        go build -ldflags="-s -w" -o ${{ github.action_path }}/mountain main.go
      shell: bash

    - name: run
      run: ${{ github.action_path }}/mountain
      shell: bash

    - name: copy preview file
      shell: bash
      run: |
        cd README.Mountain
        ls
        if [ ! -f "${{ github.action_path }}/output/preview.md" ]; then
          cp "./output/preview.md" "${{ github.action_path }}/output/preview.md"
          echo "File copied."
        else
          echo "File already exists."
        fi