name: ci

on:
  push:
  pull_request:

jobs:
  test:
    name: test Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with: 
          go-version: ^1.21
      - name: Run Test
        run: go test -v ./...
  build:
    name: format Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: Run format
        run: gofumpt -l -w .
